### ISSUE TITLE
Reporte escrito 

### ISSUE THREAD

**Issue by jreyesgar93** [jreyesgar93/practica-final-opt-2021#7]
- [x] Qué características tiene el problema de optimización?

- [x] ¿Qué tipo de problema de optimización es?

- [x] Entendimiento del método de optimización utilizado (vía una implementación por ejemplo).

- [x] ¿Qué métodos existen para resolver el problema de optimización?

- [x] ¿Cómo están resolviendo los métodos el problema de optimización?

**Comment by yefovar** [comment]
Ajustes de acuerdo a los requerimientos del proyecto
